### ISSUE TITLE
Paint filesystem

### ISSUE THREAD

**Issue by sirnewton01** [rjkroege/paint#1]
This project looks really old and perhaps orphaned but I thought I would post this idea here anyway in case it is useful.

Acme provides a filesystem to child processes giving them access to internal state of the acme editor forming a kind of plugin system that is accessible to any script or command that can read/write files on the filesystem. It's a truly unique concept that allows the editor to fold back onto the OS as its plugin system.

I often wondered if pain programs could benefit from a similar abstraction instead of inventing their own plugin systems like gimp/photoshop. Perhaps paint could expose a filesystem that can be accessed in order to select a tool, move the tool around the canvas and perform the actions that the tool allows. I think that if it is designed to be simple enough you could execute various Unix/Plan9[port] commands such as grep/awk/echo and such in order to draw pictures.

**Comment by rjkroege** [comment]
My intent here (in case that wasn't obvious) was to write the simplest code that I could that would let me make sure that I could build a graphical app using the Go version of the Plan9 graphics library. 

Your idea is however very interesting. Someday it would be nice to write a paint program and the idea of it being a filesystem has enormous potential. There's no reason for example why each layer can't be a separate file. Perhaps they could even be versioned in various ways.

This particular repository however isn't that project though. I have to finish [rjkroege/edwood](https://github.com/rjkroege/edwood) first before I can start writing a paint program. 😊
